baseURL = "https://acassio.xyz/"
# title = "Hugo Themes"
author = "Gabriel Acassio Correia"
copyright = "© 2024, G4b0"
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
title = "Acassio"

[params]
  env = "production"
  description = "Acassio's blog"
  author = "G4b0"
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true

avatar = 'gabriel.acassio.correia@gmail.com'
  name = 'G4b0'
  bio = 'Discover fresh context'
# ------------------------------

[params.homeInfoParams]
  Title = "Acassio's Page"
  Content = """
 Welcome to my page :)
- Here, I share insights and experiences that span across my technical expertise, professional journey, academic pursuits, and personal interests.
- Whether you're here to explore innovative ideas, learn about my projects, or simply get to know me better, I hope you enjoy.
- Best regards,
- Gabriel Acassio Correia.
"""

  [[params.socialIcons]]
  name = "github"
  title = "View my Github"
  url = "https://github.com/GacAcassio"

  [[params.socialIcons]]
  name = "Instagram"
  title = "See me on intsagrram :)"
  url = "https://www.instagram.com/gab_acassio/"

  [[params.socialIcons]]
  name = "Linkedin"
  title = "See me on Linkedin. :)"
  url = "https://www.linkedin.com/in/gabriel-acassio-correia-581887197/"
  
# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 10
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

  [[menu.main]]
    identifier = "Archive"
    name = "Archive"
    url = "archives"
    weight = 5

[[menu.main]]
  identifier = "Tags"
  name = "Tags"
  url = "tags/"
  weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
