baseURL = "https://acassio.xyz/"
# title = "Hugo Themes"
author = "Steve Francia"
copyright = "© 2024, lee.so"
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
title = "Acassio"

[params]
  color = 'linen'
  github = 'nanxiaobei'
  instagram = 'nan.xiaobei'

avatar = 'gabriel.acassio.correia@gmail.com'
  name = 'Gabriel'
  bio = 'Discover fresh context'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
